<<<<<<< HEAD
theme: jekyll-theme-leap-day
#theme: jekyll-theme-dinky
baseurl: /
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
  -
    scope:
      path: "5.1"
      type: "pages"
    values:
      layout: "doc"

nav_list:
  Home: ['Home', '/', 'fa-home']
  Documentaion: ['Doc', '/5.1/docs/index', 'fa-book']
=======
theme: jekyll-theme-dinky
>>>>>>> 647c7d579c96d0c504b069266856c2ee93b82b98
